django/mysite/movies/urls.py
from django.conf.urls import url

from . import views

app_name = 'movies'
urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^(?P<movie_id>[0-9]+)/$', views.detail, name='detail'),
	url(r'^(?P<movie_id>[0-9]+)/rate/$', views.rate, name='rate'),
	url(r'^search$', views.search, name='search'),
]

django/mysite/mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views

from django.views.generic.edit import CreateView
from django.contrib.auth.forms import UserCreationForm

from movies import views as movies_views

urlpatterns = [
	url(r'^$', movies_views.index),
	url(r'^login/$', auth_views.login, name='login'),
	url(r'^logout/$', auth_views.logout, name='logout'),
	url(r'^register/$', CreateView.as_view(
            template_name='registration/register.html',
            form_class=UserCreationForm,
            success_url='/',
		),			
		name='register',
	),
	
	url(r'^admin/', admin.site.urls),
	url(r'^polls/', include('polls.urls')),
	url(r'^movies/', include('movies.urls')),
]

django/mysite/polls/urls.py
from django.conf.urls import url

from . import views

app_name = 'polls'
urlpatterns = [
	# ex: /polls/
	url(r'^$', views.IndexView.as_view(), name='index'),
	# ex: /polls/5/
	url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
	# ex: /polls/5/results/
	url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
	# ex: /polls/5/vote/
	url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

django/mysite/movies/models.py
from __future__ import unicode_literals

from django.db import models
from django.utils.encoding import python_2_unicode_compatible

# Create your models here.
@python_2_unicode_compatible
class Movie(models.Model):
	movie_title = models.CharField(max_length=100)
	pub_date = models.DateTimeField('date published')
	avgrating = models.IntegerField(default=0)
	director = models.CharField(max_length=100)
	movie_cover = models.CharField(max_length=400)
	movie_genre = models.CharField(max_length=100)
	def __str__(self):
		return self.movie_title

@python_2_unicode_compatible
class Rating(models.Model):
	movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
	rate_user = models.CharField(max_length=100)
	intrating = models.IntegerField(default=5) #
	comment = models.CharField(max_length=200)
	def __str__(self):
		return self.rate_user+'RATING'+self.movie.movie_title
	def getRating(self):
		return self.intrating

django/mysite/polls/models.py
from __future__ import unicode_literals

import datetime
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils import timezone

# Create your models here.
@python_2_unicode_compatible
class Question(models.Model):
	question_text = models.CharField(max_length=200)
	pub_date = models.DateTimeField('date published')
	def __str__(self):
		return self.question_text
	def was_published_recently(self):
		now = timezone.now()
		return now - datetime.timedelta(days=1) <= self.pub_date <= now
	was_published_recently.admin_order_field = 'pub_date'
	was_published_recently.boolean = True
	was_published_recently.short_description = 'Published recently?'

@python_2_unicode_compatible
class Choice(models.Model):
	question = models.ForeignKey(Question, on_delete=models.CASCADE)
	choice_text = models.CharField(max_length=200)
	votes = models.IntegerField(default=0)
	def __str__(self):
		return self.choice_text

django/mysite/movies/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404

from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.http import Http404
from django.urls import reverse

from django.template import loader

from django.db.models import Avg
from django.db.models import Max

from .models import Movie, Rating

# Create your views here.
def index(request):
	# limited_movie_list
	ob = request.POST.get('orderby', 'id')
	limited_movie_list = Movie.objects.order_by(ob)
	# hottest
	max_rating = Movie.objects.all().aggregate(Max('avgrating')).values()[0]
	max_movie_list = Movie.objects.filter(avgrating=max_rating) #[:3]
	# personal
	recommend = []
	if request.user.is_authenticated():
		user_name = request.user.username
		user_ratings = Rating.objects.filter(rate_user=user_name)
		if user_ratings:
			max_user_rating = user_ratings.aggregate(Max('intrating')).values()[0]
			user_genre = user_ratings.filter(intrating=max_user_rating)[0].movie.movie_genre
			recommend = Movie.objects.filter(movie_genre=user_genre).order_by('avgrating')[:1]

	context = {
		'limited_movie_list': limited_movie_list,
		'max_movie_list': max_movie_list,
		'personal_movie_list':recommend,
	}
	return render(request, 'movies/index.html', context)
	
def detail(request, movie_id):
	movie = get_object_or_404(Movie, pk=movie_id)
	return render(request, 'movies/detail.html', {'movie': movie,})

def rate(request, movie_id):
	movie = get_object_or_404(Movie, pk=movie_id)
	try:
		rating = movie.rating_set.get(rate_user=request.user.username)
	except Rating.DoesNotExist:
		movie.rating_set.create(
		rate_user=request.user.get_username(),
		intrating=request.POST['rating'],
		comment=request.POST['comment'],)
	else:
		rating.intrating=request.POST['rating']
		rating.comment=request.POST['comment']
		rating.save()
	movie.avgrating = movie.rating_set.aggregate(Avg('intrating')).values()[0]
	movie.save()
	
	return HttpResponseRedirect(reverse('movies:detail', args=(movie.id,)))

def search(request):
	search_title = request.POST.get('searchcontent', '')
	try:
		movie = Movie.objects.get(movie_title=search_title)
		#get_object_or_404(Movie, movie_title=search_title)
	except Movie.DoesNotExist:
		raise Http404("Movie does not exist")
	
	return render(request, 'movies/detail.html', {'movie': movie,})
	

django/mysite/polls/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from .models import Choice, Question

# Create your views here.

class IndexView(generic.ListView):
	template_name = 'polls/index.html'
	context_object_name = 'latest_question_list'
	
	def get_queryset(self):
		return Question.objects.filter(
			pub_date__lte=timezone.now()
		).order_by('-pub_date')[:5]
	
class DetailView(generic.DetailView):
	model = Question
	template_name = 'polls/detail.html'
	
	def get_queryset(self):
		return Question.objects.filter(pub_date__lte=timezone.now())
	
class ResultsView(generic.DetailView):
	model = Question
	template_name = 'polls/results.html'
	
def vote(request, question_id):
	question = get_object_or_404(Question, pk=question_id)
	try:
		selected_choice = question.choice_set.get(pk=request.POST['choice'])
	except (KeyError, Choice.DoesNotExist):
		return render(request, 'polls/detail.html', {
			'question': question,
			'error_message': "You didn't select a choice.",
		})
	else:
		selected_choice.votes += 1
		selected_choice.save()
		return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

django/mysite/movies/templates/movies/detail.html
<!DOCTYPE html>
<html>
<head>
	<title>Detail</title>
	<link rel="stylesheet" type="text/css" href="/static/admin/css/base.css" />
</head>

<body>
<div id="header">
  <div id="branding"><h1><strong>{{ movie.movie_title }}</strong></h1></div>
</div>

<a href="{% url 'movies:index' %}">Return to movie list</a>
{% if error_message %}
	<p><strong>{{ error_message }}</strong></p>
{% endif %}

<div id='movieinfo'>
<p><img src={{movie.movie_cover}} alt='cover'></p>
<p>Director: {{movie.director}} | Date: {{movie.pub_date}}</p>
<p><strong>Average Rating: {{movie.avgrating}}</strong></p>	
</div><br>
<hr><br>

{% if user.is_authenticated %}
<div id='movierating'>
<form action="{% url 'movies:rate' movie.id %}" method="post">
{% csrf_token %}
<style type="text/css">
    .fieldset-auto-width {display: inline-block;}
</style>
<fieldset class="fieldset-auto-width">
	<legend><h2>Rate this movie:</h2></legend>
	<!--Rating: <input type="number" name="rating" min="1" max="10" />-->
	<label for="rangeinput">Rating</label> 
	<input id="rangeinput" type="range" name="rating" min="0" max="10" value="5" onchange="rangevalue.value=value"></input> 
	<output id="rangevalue">5</output><br>
	Comment: <br>
	<textarea name="comment" rows="5" cols="40"></textarea><br>
	<input type="submit" value="Rate" />
</fieldset>
</form>
{% endif %}

{% if movie.rating_set %}
    <ul>
    {% for rating in movie.rating_set.all%}
        <li>{{ rating.rate_user }}, {{ rating.intrating }}, {{ rating.comment }}</li>
    {% endfor %}
    </ul>
{% else %}
    <p>No ratings are available.</p>
{% endif %}
</div>

</body>
</html>

django/mysite/movies/templates/movies/index.html
<!DOCTYPE html>
<html>
<head>
	<title>Movies</title>
	<link rel="stylesheet" type="text/css" href="/static/admin/css/base.css" />
</head>

<body>
<div id="header">
  <div id="branding"><h1>Movie list</h1></div>
</div>

{% if user.is_authenticated %}
    <p>Welcome, {{ user.username }}. Thanks for logging in. <a href={% url 'logout' %}>Log out</a></p>
{% else %}
    <p>Welcome, guest. Please <a href={% url 'login' %}>Log in</a>. Or you can 
	<a href={% url 'register' %}>New user register</a>
	</p>
{% endif %}
<hr>

<div id='recommendations'>
	<h2>Recommended for you:</h2>
	<table>
	<tr>
	{% for movie in max_movie_list %}
        <td>
		<a href="{% url 'movies:detail' movie.id %}">{{ movie.movie_title }}</a><br>
		<img src={{movie.movie_cover}} alt='cover' width=100 height=100>
		</td>
	{% endfor %}
	{% if user.is_authenticated %}
	{% for movie in personal_movie_list %}
        <td>
		<a href="{% url 'movies:detail' movie.id %}">{{ movie.movie_title }}</a><br>
		<img src={{movie.movie_cover}} alt='cover' width=100 height=100>
		</td>
	{% endfor %}
	{% endif %}
	</tr>
	</table>
</div>
<hr>

<form action="{% url 'movies:index' %}" method="post">
{% csrf_token %}
	<button type="submit" name='orderby' value="movie_title">Name</button>
	<button type="submit" name='orderby' value="pub_date" >Date</button>
	<button type="submit" name='orderby' value="-avgrating">Top Rating</button>
</form>

{% if limited_movie_list %}
	<table>
	<thead>
		<tr>
		<th>Title</th><th>Date</th><th>Ratings</th>
		</tr>
	</thead>
	
	<tbody>
    {% for movie in limited_movie_list %}
		<tr>
        <td><a href="{% url 'movies:detail' movie.id %}">{{ movie.movie_title }}</a></td>
		<td>{{ movie.pub_date }}</td>
		<td>{{ movie.avgrating }}</td>
		</tr>
	{% endfor %}
	</tbody>
	</table>
{% else %}
    <p>No movies are available.</p>
{% endif %}

<form action="{% url 'movies:search' %}" method="post">
{% csrf_token %}
	<input type="text" name='searchcontent' value=''>
	<button type="submit" value="search">Search Movie!</button>
</form>

</body>
</html>

django/mysite/polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
	<input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
	<label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>

django/mysite/polls/templates/polls/index.html
{% load static %}

<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />

{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

django/mysite/polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>